# Generated by Django 4.0 on 2023-08-18 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('USER_ID', models.CharField(default='USER_ID', max_length=20, primary_key=True, serialize=False)),
                ('PASSWORD', models.CharField(default='PASSWORD', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('PET_BREED', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('PET_METHOD', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('PET_ID', models.AutoField(primary_key=True, serialize=False)),
                ('PET_NAME', models.CharField(max_length=50)),
                ('PET_GENDER', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('PET_NEUTER', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('PET_BIRTH', models.DateField()),
                ('WALK_TIME', models.CharField(max_length=50)),
                ('PET_BREED', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cookie.breed')),
            ],
        ),
        migrations.CreateModel(
            name='Walk',
            fields=[
                ('WALK_PLACE', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('WALK_METHOD', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SkinInfo',
            fields=[
                ('PET_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cookie.pet')),
                ('SKIN_TYPE', models.CharField(max_length=20)),
                ('THERAPY', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='pet',
            name='WALK_PLACE',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cookie.walk'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('USER_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cookie.accounts')),
                ('USER_NAME', models.CharField(max_length=80)),
                ('PET_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cookie.pet')),
            ],
        ),
    ]
