# Generated by Django 4.0 on 2023-08-20 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookie', '0002_alter_pet_pet_breed_alter_pet_walk_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='PET_BREED',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pet',
            name='WALK_PLACE',
            field=models.CharField(max_length=50),
        ),
    ]
