# Generated by Django 4.0 on 2023-08-20 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookie', '0003_alter_pet_pet_breed_alter_pet_walk_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='PET_BREED',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookie.breed'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='WALK_PLACE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookie.walk'),
        ),
    ]
