# Generated by Django 4.0 on 2023-08-21 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookie', '0004_alter_pet_pet_breed_alter_pet_walk_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='PET_BIRTH',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='PET_BREED',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cookie.breed'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='PET_GENDER',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='PET_NAME',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='PET_NEUTER',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='WALK_PLACE',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cookie.walk'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='WALK_TIME',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
